import type { Metadata } from "next";
import { Montserrat as Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";

import "./globals.css";


const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Server actions and zod validations",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Toaster 
          position="top-right"
        />
      </body>
    </html>
  );
}
